### ISSUE TITLE
Crash on applying custom icon

### ISSUE THREAD

**Issue by rektdeckard** [jahirfiquitiva/Blueprint#161]
- [x] I have verified that I am using the latest version.
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

### Device/App info:
 - Blueprint Version: `1.4.5`
 - Android version: `7.1.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto E4`

### Describe the bug
While attempting to apply a custom icon (using Nova Launcher), app crashes when new icon selected from within `IconsFragment` and `pickIcon()` invoked.

### Reproduction Steps
1. Have Nova Launcher
2. Long-press an icon to enter icon picker dialog
3. Press `open in app` toolbar menu item to launch `IconsFragment`
4. Tap an icon to apply (nothing happens)
4. Tap an icon again to apply (causes crash)

### Expected behavior

1. Selected icon should be applied, 
2. User returned to home screen.

### Screenshots

![BlueprintError](https://user-images.githubusercontent.com/26732044/59169214-4f1f6400-8b07-11e9-8c8e-b40542a56fac.jpg)

### Code and/or Logs

```Gradle
[11:40 PM, 6/8/2019] Tobias Fried: 2019-06-08 23:34:43.859 24635-24635/com.tobiasfried.phosphor.classic E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1049208)
2019-06-08 23:34:44.746 24635-24635/com.tobiasfried.phosphor.classic W/Bitmap: Called getWidth() on a recycle()'d bitmap! This is undefined behavior!
2019-06-08 23:34:44.746 24635-24635/com.tobiasfried.phosphor.classic W/Bitmap: Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
2019-06-08 23:34:44.746 24635-24635/com.tobiasfried.phosphor.classic W/Bitmap: Called getConfig() on a recycle()'d bitmap! This is undefined behavior!
2019-06-08 23:34:44.747 24635-24635/com.tobiasfried.phosphor.classic D/AndroidRuntime: Shutting down VM
2019-06-08 23:34:44.748 24635-24635/com.tobiasfried.phosphor.classic E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tobiasfried.phosphor.classic, PID: 24635
    java.lang.IllegalStateException: Can't copy a recycled bitmap
        at android.graphics.Bitmap.checkRecycled(Bitmap.java:409)
        at android.graphics.Bitmap.copy(Bitmap.java:617)
        at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment$pickIcon$1.invoke(IconsFragment.kt:219)
        at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment$pickIcon$1.invoke(IconsFragment.kt:55)
        at jahirfiquitiva.libs.kext.extensions.FragmentKt.activity(Fragment.kt:39)
        at jahirfiquitiva.libs.kext.extensions.FragmentKt.activity$default(Fragment.kt:36)
        at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment.pickIcon(IconsFragment.kt:207)
        at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment.onItemClicked(IconsFragment.kt:195)
        at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment$adapter$2$2.invoke(IconsFragment.kt:71)
        at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment$adapter$2$2.invoke(IconsFragment.kt:55)
        at jahirfiquitiva.libs.blueprint.ui.adapters.viewholders.IconViewHolder$bind$$inlined$with$lambda$2.onClick(IconViewHolder.kt:106)
        at android.view.View.performClick(View.java:5640)
        at android.view.View$PerformClick.run(View.java:22455)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by rektdeckard** [comment]
This also appears in the logs as soon as the `IconsFragment` loads:
``` Gradle
2019-06-10 01:23:42.142 13081-13081/com.tobiasfried.phosphor.classic W/AHBottomNavigation: The items list should have at least 3 items
2019-06-10 01:23:42.143 13081-13081/com.tobiasfried.phosphor.classic W/AHBottomNavigation: The items list should have at least 3 items
2019-06-10 01:23:42.144 13081-13081/com.tobiasfried.phosphor.classic W/AHBottomNavigation: The items list should have at least 3 items
2019-06-10 01:23:42.145 13081-13081/com.tobiasfried.phosphor.classic W/AHBottomNavigation: The items list should have at least 3 items
2019-06-10 01:23:42.146 13081-13081/com.tobiasfried.phosphor.classic W/AHBottomNavigation: The items list should have at least 3 items
2019-06-10 01:23:42.147 13081-13081/com.tobiasfried.phosphor.classic W/AHBottomNavigation: The items list should have at least 3 items
2019-06-10 01:23:42.147 13081-13081/com.tobiasfried.phosphor.classic W/AHBottomNavigation: The items list should have at least 3 items
2019-06-10 01:23:42.177 13081-13081/com.tobiasfried.phosphor.classic W/DynamicFragmentsPagerAdapter: Use getItemAt() because you're recreating the fragment, instead of getting the existent instance.
2019-06-10 01:23:42.177 13081-13081/com.tobiasfried.phosphor.classic W/DynamicFragmentsPagerAdapter: Use getItemAt() because you're recreating the fragment, instead of getting the existent instance.
2019-06-10 01:23:42.178 13081-13081/com.tobiasfried.phosphor.classic W/DynamicFragmentsPagerAdapter: Use getItemAt() because you're recreating the fragment, instead of getting the existent instance.
2019-06-10 01:23:42.178 13081-13081/com.tobiasfried.phosphor.classic W/DynamicFragmentsPagerAdapter: Use getItemAt() because you're recreating the fragment, instead of getting the existent instance.
2019-06-10 01:23:42.178 13081-13081/com.tobiasfried.phosphor.classic W/DynamicFragmentsPagerAdapter: Use getItemAt() because you're recreating the fragment, instead of getting the existent instance.
2019-06-10 01:23:43.171 13081-13105/com.tobiasfried.phosphor.classic W/ResourceType: Invalid package identifier when getting bag for resource number 0x00000000
2019-06-10 01:23:55.106 13081-13081/com.tobiasfried.phosphor.classic E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1049216)
...
```
