### ISSUE TITLE
Violation of Families Policy Requirements

### ISSUE THREAD

**Issue by pxflow** [jahirfiquitiva/Blueprint#174]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.4.6`
 - Android version: `9.0`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mi A2`

### Describe the bug
Terms violation issue when trying to publish an app on Google Play

Error message:
Application Stability
During testing, we had stability issues with your app and were unable to successfully assess policy compliance. Make sure your application behaves predictably at runtime and does not lock, block, or display error messages.

### Reproduction Steps
1. Publish app to Play Store
2. Publication rejected for violation of terms

### Expected behavior
1. Publish app to Play Store
2. Publication accepted by the Play Store

### Code and/or Logs

``` 
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/TextView;->mCursorDrawableRes:I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Class.java)
	at ca.allanwang.kau.utils.ColorUtilsKt.a(ColorUtilsKt.java:43)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.tint(CustomSearchView.java:30)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.tint$default(CustomSearchView.java:5)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.init(CustomSearchView.java:71)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.<init>(CustomSearchView.java:32)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.<init>(CustomSearchView.java:10)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.<init>(CustomSearchView.java:6)
	at java.lang.reflect.Constructor.newInstance0(Constructor.java)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:20)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:134)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.b(SupportMenuInflater.java:17)
	at androidx.appcompat.view.SupportMenuInflater.a(SupportMenuInflater.java:124)
	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:25)
	at jahirfiquitiva.libs.blueprint.ui.activities.BaseBlueprintActivity.onCreateOptionsMenu(BaseBlueprintActivity.java:6)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:27)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/TextView;->mEditor:Landroid/widget/Editor;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Class.java)
	at ca.allanwang.kau.utils.ColorUtilsKt.a(ColorUtilsKt.java:64)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.tint(CustomSearchView.java:30)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.tint$default(CustomSearchView.java:5)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.init(CustomSearchView.java:71)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.<init>(CustomSearchView.java:32)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.<init>(CustomSearchView.java:10)
	at jahirfiquitiva.libs.kext.ui.widgets.CustomSearchView.<init>(CustomSearchView.java:6)
	at java.lang.reflect.Constructor.newInstance0(Constructor.java)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:20)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:134)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.b(SupportMenuInflater.java:17)
	at androidx.appcompat.view.SupportMenuInflater.a(SupportMenuInflater.java:124)
	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:25)
	at jahirfiquitiva.libs.blueprint.ui.activities.BaseBlueprintActivity.onCreateOptionsMenu(BaseBlueprintActivity.java:6)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:27)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at androidx.appcompat.widget.ViewUtils.b(ViewUtils.java:19)
	at androidx.appcompat.app.AppCompatDelegateImpl.t(AppCompatDelegateImpl.java:272)
	at androidx.appcompat.app.AppCompatDelegateImpl.s(AppCompatDelegateImpl.java:4)
	at androidx.appcompat.app.AppCompatDelegateImpl.addContentView(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.getMenuInflater(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.initializePanelMenu(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.onSaveInstanceState(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.startSupportActionModeFromWindow(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:4)
	at jahirfiquitiva.libs.frames.ui.activities.base.BaseFramesActivity.setContentView(BaseFramesActivity.java)
	at jahirfiquitiva.libs.blueprint.ui.activities.BaseBlueprintActivity.onCreate(BaseBlueprintActivity.java:14)
	at jahirfiquitiva.libs.blueprint.ui.activities.BottomNavigationBlueprintActivity.onCreate(BottomNavigationBlueprintActivity.java)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:184)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getMethod(Class.java:2064)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at androidx.appcompat.widget.ViewUtils.<clinit>(ViewUtils.java:23)
	at androidx.appcompat.widget.ViewUtils.makeOptionalFitsSystemWindows(ViewUtils.java)
	at androidx.appcompat.app.AppCompatDelegateImpl.t(AppCompatDelegateImpl.java:272)
	at androidx.appcompat.app.AppCompatDelegateImpl.s(AppCompatDelegateImpl.java:4)
	at androidx.appcompat.app.AppCompatDelegateImpl.addContentView(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.getMenuInflater(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.initializePanelMenu(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.onSaveInstanceState(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
	at <OR> androidx.appcompat.app.AppCompatDelegateImpl.startSupportActionModeFromWindow(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:4)
	at jahirfiquitiva.libs.frames.ui.activities.base.BaseFramesActivity.setContentView(BaseFramesActivity.java)
	at jahirfiquitiva.libs.blueprint.ui.activities.BaseBlueprintActivity.onCreate(BaseBlueprintActivity.java:14)
	at jahirfiquitiva.libs.blueprint.ui.activities.BottomNavigationBlueprintActivity.onCreate(BottomNavigationBlueprintActivity.java)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:184)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at androidx.core.g.t.c(Unknown Source:15)
	at androidx.recyclerview.widget.bs.a(Unknown Source:102)
	at androidx.recyclerview.widget.bs.a(Unknown Source:469)
	at androidx.recyclerview.widget.bs.b(Unknown Source:5)
	at androidx.recyclerview.widget.ah.a(Unknown Source:11)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:50)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:352)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:38)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:37)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.viewpager.widget.ViewPager.onLayout(Unknown Source:259)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.b(Unknown Source:137)
	at com.google.android.material.appbar.ViewOffsetBehavior.a(Unknown Source:0)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.a(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:39)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/AutoCompleteTextView;->doAfterTextChanged()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getMethod(Class.java:2064)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at androidx.appcompat.widget.SearchView$AutoCompleteTextViewReflector.<init>(SearchView.java:28)
	at androidx.appcompat.widget.SearchView.<clinit>(SearchView.java:2)
	at java.lang.reflect.Constructor.newInstance0(Constructor.java)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:20)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:134)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.b(SupportMenuInflater.java:17)
	at androidx.appcompat.view.SupportMenuInflater.a(SupportMenuInflater.java:124)
	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:25)
	at jahirfiquitiva.libs.blueprint.ui.activities.BaseBlueprintActivity.onCreateOptionsMenu(BaseBlueprintActivity.java:6)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:27)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/AutoCompleteTextView;->doBeforeTextChanged()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getMethod(Class.java:2064)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at androidx.appcompat.widget.SearchView$AutoCompleteTextViewReflector.<init>(SearchView.java:11)
	at androidx.appcompat.widget.SearchView.<clinit>(SearchView.java:2)
	at java.lang.reflect.Constructor.newInstance0(Constructor.java)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:20)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:134)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.b(SupportMenuInflater.java:17)
	at androidx.appcompat.view.SupportMenuInflater.a(SupportMenuInflater.java:124)
	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:25)
	at jahirfiquitiva.libs.blueprint.ui.activities.BaseBlueprintActivity.onCreateOptionsMenu(BaseBlueprintActivity.java:6)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:27)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/AutoCompleteTextView;->ensureImeVisible(Z)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at androidx.appcompat.widget.SearchView$AutoCompleteTextViewReflector.<init>(SearchView.java:49)
	at androidx.appcompat.widget.SearchView.<clinit>(SearchView.java:2)
	at java.lang.reflect.Constructor.newInstance0(Constructor.java)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:20)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.a(SupportMenuInflater.java:134)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.b(SupportMenuInflater.java:17)
	at androidx.appcompat.view.SupportMenuInflater.a(SupportMenuInflater.java:124)
	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:25)
	at jahirfiquitiva.libs.blueprint.ui.activities.BaseBlueprintActivity.onCreateOptionsMenu(BaseBlueprintActivity.java:6)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:27)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jahirfiquitiva** [comment]
It seems like some Google libraries are causing this. I will provide a hotfix update, but there's no much I can do about it until Google fix it themselves

https://issuetracker.google.com/issues/123699881#comment12
