### ISSUE TITLE
Error during icon request android.os.FileUriExposedException exposed beyond app through ClipData.Item.getUri()

### ISSUE THREAD

**Issue by cosmicog** [jahirfiquitiva/Blueprint#186]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.5.0`
 - Android version: `9 - Pie`
 - Device Manufacturer: `SAMSUNG`
 - Device Name: `Galaxy s8`

### Reproduction Steps
1. Select an app(s) to request,
2. Click the blue request button (email method)
3. Result: a box saying: 

   > **Error** 
   > There was an error loading apps to request. 
    > Reason: Error: file:///storage/emulated/0/Veniverse/Requests/IconRequest-20191019_003854.zip exposed beyond app through ClipData.Item.getUri(). Please try again later.
   > **OK**

### Logcat
```Gradle
2019-10-19 00:38:54.736 27367-27509/com.cosmicog.veniversics E/Blueprint: Error
    android.os.FileUriExposedException: file:///storage/emulated/0/Veniverse/Requests/IconRequest-20191019_003854.zip exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
        at android.net.Uri.checkFileUriExposed(Uri.java:2371)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:966)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10902)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10908)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10887)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
        at android.app.Activity.startActivityForResult(Activity.java:4689)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at jahirfiquitiva.libs.frames.ui.activities.base.BaseWallpaperActionsActivity.startActivityForResult(BaseWallpaperActionsActivity.kt:326)
        at android.app.Activity.startActivityForResult(Activity.java:4647)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at jahirfiquitiva.libs.frames.ui.activities.base.BaseWallpaperActionsActivity.startActivityForResult(BaseWallpaperActionsActivity.kt:320)
        at jahirfiquitiva.libs.blueprint.quest.IconRequest.sendRequestViaEmail(IconRequest.kt:803)
        at jahirfiquitiva.libs.blueprint.quest.IconRequest.access$sendRequestViaEmail(IconRequest.kt:77)
        at jahirfiquitiva.libs.blueprint.quest.IconRequest$send$3.run(IconRequest.kt:757)
        at java.lang.Thread.run(Thread.java:764)
2019-10-19 00:38:54.736 27367-27509/com.cosmicog.veniversics E/Blueprint: Error: file:///storage/emulated/0/Veniverse/Requests/IconRequest-20191019_003854.zip exposed beyond app through ClipData.Item.getUri() -- Error: file:///storage/emulated/0/Veniverse/Requests/IconRequest-20191019_003854.zip exposed beyond app through ClipData.Item.getUri()
```

**Comment by cosmicog** [comment]
I'm truly sorry for bothering. 

Manifest was clearly saying DO-NOT-REMOVE but I did while playing with the file long ago. And this error caused because of this.

```xml
        <!-- Required for files access !!! DO NOT REMOVE !!! -->
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_providers" />
        </provider>
```
