### ISSUE TITLE
App Crash When Selecting Icons

### ISSUE THREAD

**Issue by jkebwdn** [jahirfiquitiva/Blueprint#214]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Kuper Version: `?`
 - Blueprint versionh: 2.0.6
 - Android version: `10`
 - Device Manufacturer: `One Plus`
 - Device Name: `One Plus 7 Pro 5G`

### Describe the bug
App crashes and force closes when selecting an icon to use. This is happening when using KLWP, and another user is reporting the issue when selecting icons from the app editing icons using their launcher.

### Reproduction Steps
1.Open KLWP
2.Add New Image into KLWP, press the option to select iamge to use.
3.Select Icon pack.
4.Select any Icon.
5.App will force close or crash.

### Expected behavior

Icon would select with no issue.

### Code and/or Logs
[logcat.txt](https://github.com/jahirfiquitiva/Blueprint/files/4617199/logcat.txt)

### Additional context
Unsure if it makes any difference, but this is a signed debug apk export from android studio, and I do not currently have my own license key from google play console in my mainactivity.kt

**Comment by jkebwdn** [comment]
[logcat.txt](https://github.com/jahirfiquitiva/Blueprint/files/4617406/logcat.txt)

Fresh log for you :) Completely uninstalled app from device, plugged into PC, ran app directly from android studio to device.

**Comment by jahirfiquitiva** [comment]
```gradle
05-12 17:33:20.424 22844 22844 E AndroidRuntime: FATAL EXCEPTION: main
05-12 17:33:20.424 22844 22844 E AndroidRuntime: Process: dev.jahir.blueprint.app, PID: 22844
05-12 17:33:20.424 22844 22844 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@63a0f44
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:66)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:282)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1442)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.draw(View.java:21594)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20471)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20431)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20431)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20431)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20431)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20431)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20431)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20431)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:580)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:586)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:659)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3871)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3671)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2993)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1930)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8018)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:902)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
05-12 17:33:20.424 22844 22844 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
