### ISSUE TITLE
Search button causes crash while in split-screen mode

### ISSUE THREAD

**Issue by Gowsky** [jahirfiquitiva/Blueprint#26]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.1.0`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S5`

```Gradle
02-13 16:38:02.783 18865-18865/pl.patrykgoworowski.cornieicons E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: pl.patrykgoworowski.cornieicons, PID: 18865
                                                                                 java.lang.NullPointerException: You cannot start a load on a not yet attached View or a Fragment where getActivity() returns null (which usually occurs when getActivity() is called before the Fragment is attached or after the Fragment is destroyed).
                                                                                     at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:31)
                                                                                     at com.bumptech.glide.Glide.getRetriever(Glide.java:665)
                                                                                     at com.bumptech.glide.Glide.with(Glide.java:747)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment$adapter$2.invoke(IconsFragment.kt:69)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment$adapter$2.invoke(IconsFragment.kt:52)
                                                                                     at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment.getAdapter(IconsFragment.kt)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment.setAdapterItems(IconsFragment.kt:120)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.fragments.IconsFragment.doSearch(IconsFragment.kt:89)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.activities.base.BaseBlueprintActivity.doSearch$library_release(BaseBlueprintActivity.kt:539)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.activities.base.BaseBlueprintActivity$onCreateOptionsMenu$$inlined$let$lambda$2.invoke(BaseBlueprintActivity.kt:279)
                                                                                     at jahirfiquitiva.libs.blueprint.ui.activities.base.BaseBlueprintActivity$onCreateOptionsMenu$$inlined$let$lambda$2.invoke(BaseBlueprintActivity.kt:97)
                                                                                     at jahirfiquitiva.libs.kauextensions.ui.widgets.CustomSearchView$init$1.onQueryTextChange(CustomSearchView.kt:72)
                                                                                     at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1180)
                                                                                     at android.support.v7.widget.SearchView$10.onTextChanged(SearchView.java:1714)
                                                                                     at android.widget.TextView.sendOnTextChanged(TextView.java:8187)
                                                                                     at android.widget.TextView.setText(TextView.java:4483)
                                                                                     at android.widget.TextView.setText(TextView.java:4337)
                                                                                     at android.widget.EditText.setText(EditText.java:89)
                                                                                     at android.widget.TextView.setText(TextView.java:4312)
                                                                                     at android.support.v7.widget.SearchView.onActionViewExpanded(SearchView.java:1294)
                                                                                     at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.expandItemActionView(Toolbar.java:2396)
                                                                                     at android.support.v7.view.menu.MenuBuilder.expandItemActionView(MenuBuilder.java:1348)
                                                                                     at android.support.v7.view.menu.MenuItemImpl.expandActionView(MenuItemImpl.java:810)
                                                                                     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:978)
                                                                                     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
                                                                                     at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
                                                                                     at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
                                                                                     at android.view.View.performClick(View.java:5637)
                                                                                     at android.view.View$PerformClick.run(View.java:22433)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
 
###### Reproduction Steps

1. Open app in split-screen mode
2. Tap `search` icon in icons section

###### Expected Result
-

###### Actual Result
App crashes after tapping `search` icon in icons section while in split-screen mode. In addition search function doesn't work in wallpapers section in split-screen mode also. The box opens but wallappers aren't re-querried (nothing happens).

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.1.1`
