### ISSUE TITLE
crash when I click send requset on android 11

### ISSUE THREAD

**Issue by pzcn** [jahirfiquitiva/Blueprint#262]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.6`
 - Android version: `11`
 - Device Manufacturer: `Xiaomi&zuk`
 - Device Name: `xiaomi10&zuk z2`

### Describe the bug
when I submit icon request, the app will fc. I tried it twice on two different Android 11 devices. This happens on Android 11 devices. but works well on android 10.

### Reproduction Steps
1.click send requset on android 11

### Expected behavior

get a zip and ready to send but crashed

### Code and/or Logs

```
java.io.FileNotFoundException: /storage/emulated/0/Documents/icons/Requests/appfilter_20210302_212227.xml: open failed: ENOENT (No such file or directory)
 at libcore.io.IoBridge.open(IoBridge.java:492)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
 at dev.jahir.blueprint.extensions.FileKt.saveAll(Unknown Source:10)
 at dev.jahir.blueprint.extensions.FileKt.saveAll(Unknown Source:29)
 at dev.jahir.blueprint.data.requests.SendIconRequest$buildTextFiles$2.invokeSuspend(:6)
 at dev.jahir.blueprint.data.requests.SendIconRequest$buildTextFiles$2.invoke(Unknown Source:10)
 at f.c.k.p$i.T1(Unknown Source:9)
 at f.c.k.p$i.n2(:3)
 at dev.jahir.blueprint.data.requests.SendIconRequest.buildTextFiles(:2)
 at dev.jahir.blueprint.data.requests.SendIconRequest$zipFiles$2.invokeSuspend(:18)
 at i.l.j.a.a.resumeWith(:2)
 at e.a.g0.run(Unknown Source:72)
 at e.a.s1.a.A(Unknown Source:0)
 at e.a.s1.a$a.run(:5)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
 at libcore.io.Linux.open(Native Method)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
 at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7934)
 at libcore.io.IoBridge.open(IoBridge.java:478)
 ... 14 more
```

**Comment by RandleP** [comment]
Received an error message from an user, probably same issue

![Screenshot_20210424-072209](https://user-images.githubusercontent.com/11807779/115963970-59438380-a522-11eb-80c1-01a7716d4a79.jpg)
