### ISSUE TITLE
Default App Crashes On Launch

### ISSUE THREAD

**Issue by searchy2** [jahirfiquitiva/Blueprint#65]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.3`
 - Android version: `8.0.0`
 - Device Manufacturer: `Sony`
 - Device Name: `Xperia Performance X (F8131)`

```
FATAL EXCEPTION: Thread-4
    Process: jahirfiquitiva.apps.blueprint.demo, PID: 20593
    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeCollapse(TimSort.java:439)
        at java.util.TimSort.sort(TimSort.java:245)
        at java.util.Arrays.sort(Arrays.java:1498)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:201)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.sortWith(MutableCollections.kt:284)
        at jahirfiquitiva.libs.blueprint.quest.utils.AppsLoaderKt.getInstalledApps(AppsLoader.kt:34)
        at jahirfiquitiva.libs.blueprint.quest.IconRequest$loadApps$2.run(IconRequest.kt:481)
        at java.lang.Thread.run(Thread.java:764)

FATAL EXCEPTION: Thread-7
    Process: jahirfiquitiva.apps.blueprint.demo, PID: 21339
    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeCollapse(TimSort.java:439)
        at java.util.TimSort.sort(TimSort.java:245)
        at java.util.Arrays.sort(Arrays.java:1498)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:201)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.sortWith(MutableCollections.kt:284)
        at jahirfiquitiva.libs.blueprint.quest.utils.AppsLoaderKt.getInstalledApps(AppsLoader.kt:34)
        at jahirfiquitiva.libs.blueprint.quest.IconRequest$loadApps$2.run(IconRequest.kt:481)
        at java.lang.Thread.run(Thread.java:764)
```

### Reproduction Steps

1. Launch default app on phone. 

### Expected Result
No crash. Works on emulator.

### Actual Result
Crashes when run on actual phone.

**Comment by jahirfiquitiva** [comment]
@searchy2 
Thanks for the willing to help 🙂 debugging using Kotlin does not differ from when using Java... Logs will be printed the same in logcat

**Comment by jahirfiquitiva** [comment]
Closing this in favor of version `1.1.4` _(Available soon ™)_
